name: Run tests and publish dummy data as release

on: [push]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  STATA_LICENSE: ${{ secrets.STATA_LICENSE }}
jobs:
  test_model:
    runs-on: ubuntu-latest
    name: Test stata can run against the model, using dummy data
    steps:
    - name: Extract branch name
      shell: bash
      # This is a github workflow command
      # https://help.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-output-parameter
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install opensafely-cohort-extractor==1.17.1

    - name: Update codelists
      run: cohortextractor update_codelists
    - name: dos2unix
      run: sed -i 's/\r//' codelists/*.csv
    - name: Check codelists are up to date
      run: '[[ -z $(git status --porcelain codelists) ]] || (echo "Uncommitted changes to codelists detected, aborting" && exit 1)'

    - name: Generate dummy data
      run: cohortextractor generate_cohort --expectations-population=100000

    - name: Run model
      run: docker run --rm -e STATA_LICENSE --mount source=${{ github.workspace }},dst=/workspace,type=bind ghcr.io/opensafely-core/stata-mp:latest analysis/model.do
